# Generated by Django 4.0.4 on 2022-05-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_post_vede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vede',
            new_name='file_deta',
        ),
    ]
