# Generated by Django 4.0.4 on 2022-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_rename_vede_post_file_deta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_deta',
            field=models.FileField(blank=True, null=True, upload_to='file deta'),
        ),
    ]
