# Generated by Django 4.0.5 on 2022-06-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tite',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updeta',
            new_name='update',
        ),
    ]
