# Generated by Django 4.0.5 on 2022-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_message_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_forms',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
