# Generated by Django 4.0.5 on 2022-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0014_alter_message_forms_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_forms',
            name='Year_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
