# Generated by Django 4.0.5 on 2022-07-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0015_alter_message_forms_year_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_forms',
            new_name='Message_form_user',
        ),
    ]
