# Generated by Django 4.0.5 on 2022-07-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0016_rename_message_forms_message_form_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_form_user',
            old_name='username',
            new_name='title',
        ),
    ]
