# Generated by Django 4.0.5 on 2022-07-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0017_rename_username_message_form_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_form_user',
            name='Year_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
