# Generated by Django 4.0.5 on 2022-07-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0018_alter_message_form_user_year_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_form_user',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
