# Generated by Django 4.0.5 on 2022-07-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0019_message_form_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_form_user',
            name='title',
        ),
        migrations.AddField(
            model_name='message_form_user',
            name='Text',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
