# Generated by Django 4.0.5 on 2022-07-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0020_remove_message_form_user_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_form_user',
            name='Password',
        ),
    ]
