# Generated by Django 4.0.5 on 2022-07-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0021_remove_message_form_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bode',
        ),
    ]
