# Generated by Django 4.0.5 on 2022-08-22 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0025_remove_post_data_time_post_data_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_times',
        ),
        migrations.AddField(
            model_name='post',
            name='data_itms',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 17, 18, 57, 601591, tzinfo=utc)),
        ),
    ]
