# Generated by Django 4.0.5 on 2022-08-22 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0026_remove_post_data_times_post_data_itms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_itms',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 17, 23, 32, 324847, tzinfo=utc)),
        ),
    ]
