# Generated by Django 4.0.5 on 2022-08-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0029_remove_post_data_itms_post_data_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_times',
        ),
    ]
