# Generated by Django 4.0.5 on 2022-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0030_remove_post_data_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'دسته بندی ها ', 'verbose_name_plural': 'دسته ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'گفتگو', 'verbose_name_plural': 'گفتگو ها'},
        ),
        migrations.AlterModelOptions(
            name='message_form_user',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-tima',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique_for_date='pub_deta', verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='تایم اپدیت'),
        ),
    ]
