# Generated by Django 4.0.5 on 2022-08-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0033_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظرات', 'verbose_name_plural': 'نظرات ها'},
        ),
    ]
