# Generated by Django 4.0.5 on 2022-08-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_nameusergo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nameusergo',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
