# Generated by Django 4.0.5 on 2022-08-26 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_app', '0007_alter_ticket_options_remove_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.OneToOneField(default=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
